# scriptsSQL
SQL studys

1)
SELECT  BOOK_TITLE FROM BOOKS
WHERE   SUBJECT = 'BANCO DE DADOS'
UNION
SELECT  B.BOOK_TITLE FROM BOOKS
WHERE   PUBLISHER = '%a'
  
2)
CREATE TABLE PRODUTOS17
    (COD_PROD VARCHAR2 (5) NOT NULL,
    DESCRICAO VARCHAR2 (40),
    VAL_UNIT NUMBER (8,2),
    CONSTRAINT PK_PROD PRIMARY KEY (COD_PROD));
 
INSERT INTO PRODUTOS17 (COD_PROD,DESCRICAO,VAL_UNIT)
VALUES ('01','ARROZ',2.5);
 
SELECT COD_PROD, DESCRICAO,'ANTES DO AUMENTO' AS QUANTO , VAL_UNIT FROM PRODUTOS17
UNION
SELECT PD.COD_PROD, PD.DESCRICAO, 'DEPOIS DO AUMENTO' AS QUANDO,  PD.VAL_UNIT*1.1 FROM PRODUTOS17 PD
